---
- name: Install MySQL
  apt: name={{ item }} state=latest
       update_cache=yes cache_valid_time={{ apt_cache_time }}
  with_items:
  - mariadb-server
  - python-pymysql
  - python-mysqldb

- name: Configure MySQL
  template: src=99-openstack.cnf owner=root group=root mode=0644
            dest=/etc/mysql/mariadb.conf.d/99-openstack.cnf
  notify: restart mysql

- meta: flush_handlers

- name: update mysql root password for all root accounts
  mysql_user: name=root host=$item
        password="{{ lookup('password', 'passwords/mysql_root.pass') }}"
  with_items:
  - $ansible_hostname
  - newton
  - 127.0.0.1
  - ::1
  - localhost

- name: ensure anonymous users are not in the database
  mysql_user: name='' host=$item state=absent
  with_items:
    - localhost
    - newton
    - $inventory_hostname

- name: remove the test database
  mysql_db: name=test state=absent
