---
- name: Install Dashboard components
  apt: name={{ item }} state=latest
       update_cache=yes cache_valid_time={{ apt_cache_time }}
  with_items:
  - openstack-dashboard

- name: Configure Dashboard
  template: src=local_settings.py.j2 dest=/etc/openstack-dashboard/local_settings.py
            owner=root group=root mode=0644
  notify:
  - restart apache

- meta: flush_handlers
