---
admin_pass: "{{ lookup('password', 'passwords/admin.pass') }}"
rabbit_pass: "{{ lookup('password', 'passwords/rabbit.pass') }}"
barbicandb_pass: "{{ lookup('password', 'passwords/barbicandb.pass') }}"
barbican_pass: "{{ lookup('password', 'passwords/barbican.pass') }}"
admin_env:
  OS_USERNAME: "admin"
  OS_PASSWORD: "{{ admin_pass }}"
  OS_PROJECT_NAME: "admin"
  OS_USER_DOMAIN_NAME: "Default"
  OS_PROJECT_DOMAIN_NAME: "Default"
  OS_AUTH_URL: "http://controller:35357/v3"
  OS_IDENTITY_API_VERSION: "3"
