---
admin_pass: "{{ lookup('password', 'passwords/admin.pass') }}"
mysql_root_pass: "{{ lookup('password', 'passwords/mysql_root.pass') }}"
rabbit_pass: "{{ lookup('password', 'passwords/rabbit.pass') }}"
swiftdb_pass: "{{ lookup('password', 'passwords/swiftdb.pass') }}"
swift_pass: "{{ lookup('password', 'passwords/swift.pass') }}"
admin_env:
  OS_USERNAME: "admin"
  OS_PASSWORD: "{{ admin_pass }}"
  OS_PROJECT_NAME: "admin"
  OS_USER_DOMAIN_NAME: "Default"
  OS_PROJECT_DOMAIN_NAME: "Default"
  OS_AUTH_URL: "http://controller:35357/v3"
  OS_IDENTITY_API_VERSION: "3"
swift_disk1: "{{ ( ansible_devices.keys() | select('match', '[vs]d.*') | list | sort)[2] }}"
swift_disk2: "{{ ( ansible_devices.keys() | select('match', '[vs]d.*') | list | sort)[3] }}"
swift_hash: "{{ lookup('password', 'passwords/swift_hash.pass') }}"
