---
- name: Get provider network NIC name
  get_provider_nic: interfaces_path="/etc/network/interfaces"
                    networks_path="/sys/class/net"

- name : Create Neutron database
  mysql_db: name=neutron state=present
  notify:
  - create neutron user in keystone

- name: Configure Neutron database user
  mysql_user: name=neutron
          password="{{ neutrondb_pass }}"
          priv="neutron.*:ALL,GRANT"
          host="{{ item }}"
  with_items:
    - localhost
    - "%"

- meta: flush_handlers

- name: Grant neutron user access to service project via admin role
  os_user_role: user=neutron role=admin project=service state=present
  environment: "{{ admin_env }}"

- name: Create Neutron service in Keystone
  os_keystone_service: state=present name=neutron service_type=network
               description="OpenStack Compute Service"
               public_endpoint="http://controller:9696"
               internal_endpoint="http://controller:9696"
               admin_endpoint="http://controller:9696"
               region=RegionOne
  environment: "{{ admin_env }}"

- name: Install Neutron components
  apt: name={{ item }} state=latest
       update_cache=yes cache_valid_time={{ apt_cache_time }}
  with_items:
  - neutron-server
  - neutron-plugin-ml2
  - neutron-linuxbridge-agent
  - neutron-l3-agent
  - neutron-dhcp-agent
  - neutron-metadata-agent

- name: Configure neutron.conf
  template: src=neutron.conf.j2 dest=/etc/neutron/neutron.conf
            owner=root group=neutron mode=0640
  notify:
  - neutron db sync
  - restart neutron services

- name: Configure ml2_conf.ini
  template: src=ml2_conf.ini.j2 dest=/etc/neutron/plugins/ml2/ml2_conf.ini
            owner=root group=neutron mode=0640
  notify:
  - neutron db sync
  - restart neutron services

- name: Configure linuxbridge_agent.ini
  template: src=linuxbridge_agent.ini.j2
            dest=/etc/neutron/plugins/ml2/linuxbridge_agent.ini
            owner=root group=neutron mode=0640
  notify:
  - neutron db sync
  - restart neutron services

- name: Configure l3_agent.ini
  template: src=l3_agent.ini.j2 dest=/etc/neutron/l3_agent.ini
            owner=root group=neutron mode=0640
  notify:
  - neutron db sync
  - restart neutron services

- name: Configure dhcp_agent.ini
  template: src=dhcp_agent.ini.j2 dest=/etc/neutron/dhcp_agent.ini
            owner=root group=neutron mode=0640
  notify:
  - neutron db sync
  - restart neutron services

- name: Configure metadata_agent.ini
  template: src=metadata_agent.ini.j2 dest=/etc/neutron/metadata_agent.ini
            owner=root group=neutron mode=0640
  notify:
  - neutron db sync
  - restart neutron services

- meta: flush_handlers

- name: Wait for Neutron service to become available
  wait_for: port=9696 delay=2

- name: Create external network
  os_network: state=present name=ext_network external=true
              provider_network_type=flat
              provider_physical_network=provider
  environment: "{{ admin_env }}"

- name: Create external subnet
  os_subnet: state=present network_name=ext_network name=ext_subnet
             cidr=192.168.99.0/24 dns_nameservers=192.168.99.1
  environment: "{{ admin_env }}"
