---
- hosts: all
  vars:
    apt_cache_time: 21600
  become: true
  roles:
#  - common
#  - mysql
#  - rabbitmq
#  - memcached
#  - keystone
#  - glance
#  - nova
#  - neutron
#  - horizon
  - finish
